version: "3.9"
services:
  worker:
    build: .
    environment:
      HNDLR: 
      SESSION_NAME: $SESSION_NAME
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      SUDO_USERS: $SUDO_USERS  # defaults to None
      UPDATES_CHANNEL: $UPDATES_CHANNEL  # defaults to None
      BOT_TOKEN: $BOT_TOKEN  # defaults to None
      BOT_USERNAME: $BOT_USERNAME  # defaults to None
      ASSISTANT_NAME: $ASSISTANT_NAME  # defaults to None
      GROUP_SUPPORT: $GROUP_SUPPORT  # defaults to None
      BOT_NAME: $BOT_NAME  # defaults to None
      OWNER_NAME: $OWNER_NAME  # defaults to None
